In [19]:
%load_ext autoreload
%autoreload 2
import warnings
warnings.filterwarnings('ignore')
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import pandas as pd
import numpy as np
import lightgbm as lgbm
import catboost as ctb
import os
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import json
import time
import pickle

from tqdm import tqdm

from utils import load_json
from features import QuarterlyFeatures, QuarterlyDiffFeatures, BaseCompanyFeatures, FeatureMerger
from targets import QuarterlyTarget, QuarterlyDiffTarget
from models import GroupedOOFModel, TimeSeriesOOFModel, AnsambleModel, LogExpModel
from pipelines import BasePipeline
from data import SF1Data
from metrics import median_absolute_relative_error
sns.set()

config = load_json("config.json")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
data_loader = SF1Data(config['sf1_data_path'])
tickers_df = data_loader.load_tickers(
    currency='USD',
    scalemarketcap=['4 - Mid', '5 - Large', '6 - Mega'])
ticker_list = tickers_df['ticker'].unique().tolist()

In [4]:
config['sf1_data_path'] = '../clever_investment_data/cf1_13_01_2021'

In [20]:
columns = ['revenue', 'netinc', 'ncf', 'assets', 'ebitda', 'debt', 'fcf',
           'gp', 'workingcapital', 'cashneq', 'rnd', 'sgna', 'ncfx',
           'divyield', 'currentratio', 'netinccmn']

cat_columns = ['sector', 'sicindustry']

fc1 = QuarterlyFeatures(columns=columns,
                        quarter_counts=[2, 4, 10],
                        max_back_quarter=10)

fc2 = BaseCompanyFeatures(cat_columns=cat_columns)

fc3 = QuarterlyDiffFeatures(columns=columns,
                            compare_idxs=[1, 4],
                            max_back_quarter=10)

feature = FeatureMerger(fc1, fc2, on='ticker')

# feature = FeatureMerger(feature, fc3, on=['ticker', 'date'])


target = QuarterlyTarget(col='marketcap', quarter_shift=0)
#target = QuarterlyDiffTarget(col='marketcap')

base_model = AnsambleModel(base_models=[LogExpModel(lgbm.sklearn.LGBMRegressor()),
                                        LogExpModel(ctb.CatBoostRegressor(verbose=False))], 
                           bagging_fraction=0.7, model_cnt=20)

model = GroupedOOFModel(ctb.CatBoostRegressor(verbose=False),
                        group_column='ticker', fold_cnt=5)

model = TimeSeriesOOFModel(ctb.CatBoostRegressor(verbose=False),
                           time_column='date', fold_cnt=5)

mc_pipeline = BasePipeline(feature, target, model, median_absolute_relative_error)
mc_pipeline.fit(config, ticker_list)
#mc_pipeline.export_core('models_data/diff')

3874it [00:27, 139.11it/s]
2401it [00:03, 675.93it/s]

nan

In [23]:
x = np.array([np.nan, 10])
x[~np.isnan(x)]

array([], dtype=float64)

In [ ]:
0.7191348902981789 ans
0.7667987731362407
0.7691278337267149

In [ ]:
0.3238006278631045 ans
0.3226811547779296 log_exp_ctb
0.34013409255339005 log_exp_lgb
0.3731881490521315 ctb
0.38325054127451996 lgb

In [4]:
X = feature.calculate(config['sf1_data_path'], ticker_list)
y = target.calculate(config['sf1_data_path'], 
                                  X.index.to_frame(index=False))
leave_mask = (y['y'].isnull() == False)
y = y[leave_mask]#.reset_index(drop=True)
X = X[leave_mask]

3874it [00:29, 132.40it/s]
2401it [00:03, 620.00it/s]

In [5]:
model.fit(X, y['y'])

0
1
2
3
4

In [6]:
    with open('{}.pickle'.format('tmp'), 'wb') as f:
        pickle.dump(model, f)

In [18]:
model.predict(X)

array([8.76774927e+08, 8.59081231e+08, 8.56702809e+08, ...,
       1.00961997e+09, 1.42488678e+09, 3.82320800e+09])

In [8]:
X

                   quarter2_revenue_mean  quarter2_revenue_median  \
ticker date
DQWS   2020-11-13               235307.5                 235307.5
       2020-08-14               374226.0                 374226.0
       2020-05-15               359828.0                 359828.0
       2020-04-03               192114.0                 192114.0
       2020-03-30               115209.5                 115209.5
...                                  ...                      ...
LSPD   2021-02-04             51552000.0               51552000.0
FROG   2021-02-12             40787500.0               40787500.0
STEP   2021-02-11            245031500.0              245031500.0
ALGM   2021-02-02            150549000.0              150549000.0
LESL   2021-02-08            263159500.0              263159500.0

                   quarter2_revenue_max  quarter2_revenue_min  \
ticker date
DQWS   2020-11-13              249705.0              220910.0
       2020-08-14              527542.0              220910.0
       2020-05-15              527542.0              192114.0
       2020-04-03              192114.0              192114.0
       2020-03-30              192114.0               38305.0
...                                 ...                   ...
LSPD   2021-02-04            57611000.0            45493000.0
FROG   2021-02-12            42689000.0            38886000.0
STEP   2021-02-11           247150000.0           242913000.0
ALGM   2021-02-02           164449000.0           136649000.0
LESL   2021-02-08           381313000.0           145006000.0

                   quarter2_revenue_std  quarter2_revenue_diff_mean  \
ticker date
DQWS   2020-11-13               14397.5                     28795.0
       2020-08-14              153316.0                   -306632.0
       2020-05-15              167714.0                    335428.0
       2020-04-03                   0.0                         0.0
       2020-03-30               76904.5                    153809.0
...                                 ...                         ...
LSPD   2021-02-04             6059000.0                  12118000.0
FROG   2021-02-12             1901500.0                   3803000.0
STEP   2021-02-11             2118500.0                   4237000.0
ALGM   2021-02-02            13900000.0                  27800000.0
LESL   2021-02-08           118153500.0                -236307000.0

                   quarter2_revenue_diff_median  quarter2_revenue_diff_max  \
ticker date
DQWS   2020-11-13                       28795.0                    28795.0
       2020-08-14                     -306632.0                  -306632.0
       2020-05-15                      335428.0                   335428.0
       2020-04-03                           0.0                        0.0
       2020-03-30                      153809.0                   153809.0
...                                         ...                        ...
LSPD   2021-02-04                    12118000.0                 12118000.0
FROG   2021-02-12                     3803000.0                  3803000.0
STEP   2021-02-11                     4237000.0                  4237000.0
ALGM   2021-02-02                    27800000.0                 27800000.0
LESL   2021-02-08                  -236307000.0               -236307000.0

                   quarter2_revenue_diff_min  quarter2_revenue_diff_std  ...  \
ticker date                                                              ...
DQWS   2020-11-13                    28795.0                        0.0  ...
       2020-08-14                  -306632.0                        0.0  ...
       2020-05-15                   335428.0                        0.0  ...
       2020-04-03                        0.0                        0.0  ...
       2020-03-30                   153809.0                        0.0  ...
...                                      ...                        ...  ...
LSPD   2021-02-04                 12118000.0                        0.0  ...
FROG   2021-02-12                  3803000.0                        0.0  ...
STEP   2021-02-11                  4237000.0                        0.0  ...
ALGM   2021-02-02                 27800000.0                        0.0  ...
LESL   2021-02-08               -236307000.0                        0.0  ...

                   compare4_fcf  compare4_gp  compare4_workingcapital  \
ticker date
DQWS   2020-11-13     -1.402517     0.736181                -0.058636
       2020-08-14     -0.357245     4.561310                 0.694273
       2020-05-15      3.586985     5.350196                 2.816845
       2020-04-03     -0.647455     3.873477                -6.466597
       2020-03-30      0.108555     3.453074                -2.234651
...                         ...          ...                      ...
LSPD   2021-02-04           NaN          NaN                      NaN
FROG   2021-02-12           NaN          NaN                      NaN
STEP   2021-02-11           NaN          NaN                      NaN
ALGM   2021-02-02           NaN          NaN                      NaN
LESL   2021-02-08           NaN          NaN                      NaN

                   compare4_cashneq  compare4_rnd  compare4_sgna  \
ticker date
DQWS   2020-11-13          1.166008           NaN       0.372814
       2020-08-14          1.308895           NaN      -0.516866
       2020-05-15          0.512900           NaN       0.132189
       2020-04-03         -0.442308           NaN      -0.542161
       2020-03-30         -0.743831           NaN      -0.247272
...                             ...           ...            ...
LSPD   2021-02-04               NaN           NaN            NaN
FROG   2021-02-12               NaN           NaN            NaN
STEP   2021-02-11               NaN           NaN            NaN
ALGM   2021-02-02               NaN           NaN            NaN
LESL   2021-02-08               NaN           NaN            NaN

                   compare4_ncfx  compare4_divyield  compare4_currentratio  \
ticker date
DQWS   2020-11-13      -0.888710                NaN               0.124283
       2020-08-14       0.579729                NaN              -0.192248
       2020-05-15      -0.168724                NaN              -0.274536
       2020-04-03     -76.354132                NaN              -0.583599
       2020-03-30       0.695825                NaN              -0.756291
...                          ...                ...                    ...
LSPD   2021-02-04            NaN                NaN                    NaN
FROG   2021-02-12            NaN                NaN                    NaN
STEP   2021-02-11            NaN                NaN                    NaN
ALGM   2021-02-02            NaN                NaN                    NaN
LESL   2021-02-08            NaN                NaN                    NaN

                   compare4_netinccmn
ticker date
DQWS   2020-11-13           -0.871435
       2020-08-14           -1.180638
       2020-05-15           -0.913871
       2020-04-03           -0.490364
       2020-03-30           -0.278100
...                               ...
LSPD   2021-02-04                 NaN
FROG   2021-02-12                 NaN
STEP   2021-02-11                 NaN
ALGM   2021-02-02                 NaN
LESL   2021-02-08                 NaN

[19768 rows x 514 columns]

In [11]:
times = X.reset_index()['date'].astype(np.datetime64).values

In [21]:
fold_cnt = 20

max_time = max(times)
min_time = min(times)
delta = (max_time - min_time) // fold_cnt

time_bounds = []
for fold_id in range(1, fold_cnt):
    time_bounds.append(min_time + fold_id * delta)
time_bounds.append(max_time)

In [54]:
delta

numpy.timedelta64(7374240000000000,'ns')

In [58]:
min_time + np.timedelta64(10000, 'D')

numpy.datetime64('2043-11-03T00:00:00.000000000')

In [48]:
min_time

numpy.datetime64('2016-06-17T00:00:00.000000000')

In [47]:
X[:0]

Empty DataFrame
Columns: [quarter2_revenue_mean, quarter2_revenue_median, quarter2_revenue_max, quarter2_revenue_min, quarter2_revenue_std, quarter2_revenue_diff_mean, quarter2_revenue_diff_median, quarter2_revenue_diff_max, quarter2_revenue_diff_min, quarter2_revenue_diff_std, quarter2_netinc_mean, quarter2_netinc_median, quarter2_netinc_max, quarter2_netinc_min, quarter2_netinc_std, quarter2_netinc_diff_mean, quarter2_netinc_diff_median, quarter2_netinc_diff_max, quarter2_netinc_diff_min, quarter2_netinc_diff_std, quarter2_ncf_mean, quarter2_ncf_median, quarter2_ncf_max, quarter2_ncf_min, quarter2_ncf_std, quarter2_ncf_diff_mean, quarter2_ncf_diff_median, quarter2_ncf_diff_max, quarter2_ncf_diff_min, quarter2_ncf_diff_std, quarter2_assets_mean, quarter2_assets_median, quarter2_assets_max, quarter2_assets_min, quarter2_assets_std, quarter2_assets_diff_mean, quarter2_assets_diff_median, quarter2_assets_diff_max, quarter2_assets_diff_min, quarter2_assets_diff_std, quarter2_ebitda_mean, quarter2_ebitda_median, quarter2_ebitda_max, quarter2_ebitda_min, quarter2_ebitda_std, quarter2_ebitda_diff_mean, quarter2_ebitda_diff_median, quarter2_ebitda_diff_max, quarter2_ebitda_diff_min, quarter2_ebitda_diff_std, quarter2_debt_mean, quarter2_debt_median, quarter2_debt_max, quarter2_debt_min, quarter2_debt_std, quarter2_debt_diff_mean, quarter2_debt_diff_median, quarter2_debt_diff_max, quarter2_debt_diff_min, quarter2_debt_diff_std, quarter2_fcf_mean, quarter2_fcf_median, quarter2_fcf_max, quarter2_fcf_min, quarter2_fcf_std, quarter2_fcf_diff_mean, quarter2_fcf_diff_median, quarter2_fcf_diff_max, quarter2_fcf_diff_min, quarter2_fcf_diff_std, quarter2_gp_mean, quarter2_gp_median, quarter2_gp_max, quarter2_gp_min, quarter2_gp_std, quarter2_gp_diff_mean, quarter2_gp_diff_median, quarter2_gp_diff_max, quarter2_gp_diff_min, quarter2_gp_diff_std, quarter2_workingcapital_mean, quarter2_workingcapital_median, quarter2_workingcapital_max, quarter2_workingcapital_min, quarter2_workingcapital_std, quarter2_workingcapital_diff_mean, quarter2_workingcapital_diff_median, quarter2_workingcapital_diff_max, quarter2_workingcapital_diff_min, quarter2_workingcapital_diff_std, quarter2_cashneq_mean, quarter2_cashneq_median, quarter2_cashneq_max, quarter2_cashneq_min, quarter2_cashneq_std, quarter2_cashneq_diff_mean, quarter2_cashneq_diff_median, quarter2_cashneq_diff_max, quarter2_cashneq_diff_min, quarter2_cashneq_diff_std, ...]
Index: []

[0 rows x 514 columns]

In [45]:
for fold_id in range(fold_cnt - 1):
    time_bounds[fold_id]
    curr_mask = (times > time_bounds[fold_id]) * (times <= time_bounds[fold_id + 1])
    
    X[curr_mask]

221
160
254
204
190
34
220
183
202
1343
1962
1974
1962
2010
1885
2034
1960
1944
815

IndexError: list index out of range

In [38]:
time_bounds[fold_id]

numpy.datetime64('2016-09-10T08:24:00.000000000')

In [33]:
times.shape

(19768,)

In [42]:
221 * 20

4420

In [44]:
len(times[(times > time_bounds[fold_id]) * (times <= time_bounds[fold_id + 1])])

1962

In [40]:
len(times[times <= time_bounds[fold_id]])

211

In [35]:
X[times <= time_bounds[fold_id]]

,,quarter2_revenue_mean,quarter2_revenue_median,quarter2_revenue_max,quarter2_revenue_min,quarter2_revenue_std,quarter2_revenue_diff_mean,quarter2_revenue_diff_median,quarter2_revenue_diff_max,quarter2_revenue_diff_min,quarter2_revenue_diff_std,...,compare4_fcf,compare4_gp,compare4_workingcapital,compare4_cashneq,compare4_rnd,compare4_sgna,compare4_ncfx,compare4_divyield,compare4_currentratio,compare4_netinccmn
ticker,date,,,,,,,,,,,,,,,,,,,,,
YHOO,2016-08-08,1.197394e+09,1.197394e+09,1.307637e+09,1.087152e+09,110242500.0,220485000.0,220485000.0,220485000.0,220485000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VNRSQ,2016-07-29,6.903250e+07,6.903250e+07,1.131990e+08,2.486600e+07,44166500.0,-88333000.0,-88333000.0,-88333000.0,-88333000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BATS,2016-08-05,4.884000e+08,4.884000e+08,5.109000e+08,4.659000e+08,22500000.0,-45000000.0,-45000000.0,-45000000.0,-45000000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEG1,2016-08-05,3.530845e+08,3.530845e+08,3.627060e+08,3.434630e+08,9621500.0,19243000.0,19243000.0,19243000.0,19243000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACTA,2016-08-05,3.565950e+07,3.565950e+07,3.670900e+07,3.461000e+07,1049500.0,2099000.0,2099000.0,2099000.0,2099000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CSC,2016-08-09,1.868500e+09,1.868500e+09,1.930000e+09,1.807000e+09,61500000.0,123000000.0,123000000.0,123000000.0,123000000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CLC,2016-06-17,3.406200e+08,3.406200e+08,3.649680e+08,3.162720e+08,24348000.0,48696000.0,48696000.0,48696000.0,48696000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BCR,2016-07-27,9.025000e+08,9.025000e+08,9.315000e+08,8.735000e+08,29000000.0,58000000.0,58000000.0,58000000.0,58000000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATW,2016-08-02,2.620740e+08,2.620740e+08,2.963510e+08,2.277970e+08,34277000.0,-68554000.0,-68554000.0,-68554000.0,-68554000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TYC,2016-07-29,2.390000e+09,2.390000e+09,2.449000e+09,2.331000e+09,59000000.0,118000000.0,118000000.0,118000000.0,118000000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
y[times <= time_bounds[fold_id]]

                          y
ticker date
YHOO   2016-08-08  0.051074
VNRSQ  2016-07-29  0.048364
BATS   2016-08-05  0.036982
MEG1   2016-08-05  0.007214
ACTA   2016-08-05  0.048425
...                     ...
CSC    2016-08-09 -0.062971
CLC    2016-06-17  0.041345
BCR    2016-07-27  0.045956
ATW    2016-08-02 -0.148395
TYC    2016-07-29  0.185042

[211 rows x 1 columns]

In [26]:
time_bounds[fold_id]

numpy.datetime64('2021-02-18T00:00:00.000000000')

In [ ]:
times

In [23]:
len(time_bounds)

20

In [22]:
time_bounds

[numpy.datetime64('2016-09-10T08:24:00.000000000'),
 numpy.datetime64('2016-12-04T16:48:00.000000000'),
 numpy.datetime64('2017-02-28T01:12:00.000000000'),
 numpy.datetime64('2017-05-24T09:36:00.000000000'),
 numpy.datetime64('2017-08-17T18:00:00.000000000'),
 numpy.datetime64('2017-11-11T02:24:00.000000000'),
 numpy.datetime64('2018-02-04T10:48:00.000000000'),
 numpy.datetime64('2018-04-30T19:12:00.000000000'),
 numpy.datetime64('2018-07-25T03:36:00.000000000'),
 numpy.datetime64('2018-10-18T12:00:00.000000000'),
 numpy.datetime64('2019-01-11T20:24:00.000000000'),
 numpy.datetime64('2019-04-07T04:48:00.000000000'),
 numpy.datetime64('2019-07-01T13:12:00.000000000'),
 numpy.datetime64('2019-09-24T21:36:00.000000000'),
 numpy.datetime64('2019-12-19T06:00:00.000000000'),
 numpy.datetime64('2020-03-13T14:24:00.000000000'),
 numpy.datetime64('2020-06-06T22:48:00.000000000'),
 numpy.datetime64('2020-08-31T07:12:00.000000000'),
 numpy.datetime64('2020-11-24T15:36:00.000000000'),
 numpy.datetime64('2021-02-18T00:00:00.000000000')]

In [211]:
time[time <= time_bounds[0]]

array(['2016-08-08T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-12T00:00:00.000000000',
       '2016-08-11T00:00:00.000000000', '2016-08-11T00:00:00.000000000',
       '2016-08-02T00:00:00.000000000', '2016-07-26T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-11T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-09-09T00:00:00.000000000',
       '2016-08-03T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-02T00:00:00.000000000',
       '2016-09-09T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-07-08T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-02T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-02T00:00:00.000000000',
       '2016-07-26T00:00:00.000000000', '2016-08-04T00:00:00.000000000',
       '2016-08-03T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-02T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-02T00:00:00.000000000', '2016-08-02T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-07-27T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-07-28T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-07-28T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-03T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-15T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-01T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-02T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-06-28T00:00:00.000000000', '2016-09-01T00:00:00.000000000',
       '2016-07-28T00:00:00.000000000', '2016-08-01T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-07-26T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-07-28T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-01T00:00:00.000000000', '2016-07-21T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-09-06T00:00:00.000000000', '2016-08-04T00:00:00.000000000',
       '2016-07-28T00:00:00.000000000', '2016-08-02T00:00:00.000000000',
       '2016-06-30T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-03T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-07-28T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-08-02T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-07-26T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-07-26T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-10T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-07-27T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-09-02T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-07-28T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000', '2016-07-08T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000', '2016-08-04T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-03T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-04T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-05T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-07-26T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-09-02T00:00:00.000000000',
       '2016-08-11T00:00:00.000000000', '2016-09-09T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-25T00:00:00.000000000',
       '2016-08-17T00:00:00.000000000', '2016-08-08T00:00:00.000000000',
       '2016-08-10T00:00:00.000000000', '2016-08-04T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-07-27T00:00:00.000000000',
       '2016-08-05T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-08-08T00:00:00.000000000', '2016-08-30T00:00:00.000000000',
       '2016-08-11T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-03T00:00:00.000000000', '2016-07-29T00:00:00.000000000',
       '2016-08-02T00:00:00.000000000', '2016-08-03T00:00:00.000000000',
       '2016-09-07T00:00:00.000000000', '2016-09-07T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000', '2016-08-15T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-08-02T00:00:00.000000000',
       '2016-08-04T00:00:00.000000000', '2016-08-09T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-07-26T00:00:00.000000000',
       '2016-08-09T00:00:00.000000000', '2016-06-17T00:00:00.000000000',
       '2016-07-27T00:00:00.000000000', '2016-08-02T00:00:00.000000000',
       '2016-07-29T00:00:00.000000000'], dtype='datetime64[ns]')

In [209]:
len(time_bounds)

19

In [208]:
time_bounds

[numpy.datetime64('2016-09-10T08:24:00.000000000'),
 numpy.datetime64('2016-12-04T16:48:00.000000000'),
 numpy.datetime64('2017-02-28T01:12:00.000000000'),
 numpy.datetime64('2017-05-24T09:36:00.000000000'),
 numpy.datetime64('2017-08-17T18:00:00.000000000'),
 numpy.datetime64('2017-11-11T02:24:00.000000000'),
 numpy.datetime64('2018-02-04T10:48:00.000000000'),
 numpy.datetime64('2018-04-30T19:12:00.000000000'),
 numpy.datetime64('2018-07-25T03:36:00.000000000'),
 numpy.datetime64('2018-10-18T12:00:00.000000000'),
 numpy.datetime64('2019-01-11T20:24:00.000000000'),
 numpy.datetime64('2019-04-07T04:48:00.000000000'),
 numpy.datetime64('2019-07-01T13:12:00.000000000'),
 numpy.datetime64('2019-09-24T21:36:00.000000000'),
 numpy.datetime64('2019-12-19T06:00:00.000000000'),
 numpy.datetime64('2020-03-13T14:24:00.000000000'),
 numpy.datetime64('2020-06-06T22:48:00.000000000'),
 numpy.datetime64('2020-08-31T07:12:00.000000000'),
 numpy.datetime64('2020-11-24T15:36:00.000000000')]

In [186]:
X.join(y)

                   quarter2_revenue_mean  quarter2_revenue_median  \
ticker date
DQWS   2020-11-13               235307.5                 235307.5
       2020-08-14               374226.0                 374226.0
       2020-05-15               359828.0                 359828.0
       2020-04-03               192114.0                 192114.0
       2020-03-30               115209.5                 115209.5
...                                  ...                      ...
LSPD   2021-02-04             51552000.0               51552000.0
FROG   2021-02-12             40787500.0               40787500.0
STEP   2021-02-11            245031500.0              245031500.0
ALGM   2021-02-02            150549000.0              150549000.0
LESL   2021-02-08            263159500.0              263159500.0

                   quarter2_revenue_max  quarter2_revenue_min  \
ticker date
DQWS   2020-11-13              249705.0              220910.0
       2020-08-14              527542.0              220910.0
       2020-05-15              527542.0              192114.0
       2020-04-03              192114.0              192114.0
       2020-03-30              192114.0               38305.0
...                                 ...                   ...
LSPD   2021-02-04            57611000.0            45493000.0
FROG   2021-02-12            42689000.0            38886000.0
STEP   2021-02-11           247150000.0           242913000.0
ALGM   2021-02-02           164449000.0           136649000.0
LESL   2021-02-08           381313000.0           145006000.0

                   quarter2_revenue_std  quarter2_revenue_diff_mean  \
ticker date
DQWS   2020-11-13               14397.5                     28795.0
       2020-08-14              153316.0                   -306632.0
       2020-05-15              167714.0                    335428.0
       2020-04-03                   0.0                         0.0
       2020-03-30               76904.5                    153809.0
...                                 ...                         ...
LSPD   2021-02-04             6059000.0                  12118000.0
FROG   2021-02-12             1901500.0                   3803000.0
STEP   2021-02-11             2118500.0                   4237000.0
ALGM   2021-02-02            13900000.0                  27800000.0
LESL   2021-02-08           118153500.0                -236307000.0

                   quarter2_revenue_diff_median  quarter2_revenue_diff_max  \
ticker date
DQWS   2020-11-13                       28795.0                    28795.0
       2020-08-14                     -306632.0                  -306632.0
       2020-05-15                      335428.0                   335428.0
       2020-04-03                           0.0                        0.0
       2020-03-30                      153809.0                   153809.0
...                                         ...                        ...
LSPD   2021-02-04                    12118000.0                 12118000.0
FROG   2021-02-12                     3803000.0                  3803000.0
STEP   2021-02-11                     4237000.0                  4237000.0
ALGM   2021-02-02                    27800000.0                 27800000.0
LESL   2021-02-08                  -236307000.0               -236307000.0

                   quarter2_revenue_diff_min  quarter2_revenue_diff_std  ...  \
ticker date                                                              ...
DQWS   2020-11-13                    28795.0                        0.0  ...
       2020-08-14                  -306632.0                        0.0  ...
       2020-05-15                   335428.0                        0.0  ...
       2020-04-03                        0.0                        0.0  ...
       2020-03-30                   153809.0                        0.0  ...
...                                      ...                        ...  ...
LSPD   2021-02-04                 12118000.0                        0.0  ...
FROG   2021-02-12                  3803000.0                        0.0  ...
STEP   2021-02-11                  4237000.0                        0.0  ...
ALGM   2021-02-02                 27800000.0                        0.0  ...
LESL   2021-02-08               -236307000.0                        0.0  ...

                   quarter10_netinccmn_diff_mean  \
ticker date
DQWS   2020-11-13                   1.223100e+04
       2020-08-14                   1.499575e+04
       2020-05-15                   1.563871e+04
       2020-04-03                   8.905667e+03
       2020-03-30                   1.068680e+04
...                                          ...
LSPD   2021-02-04                  -2.318500e+07
FROG   2021-02-12                   1.551000e+06
STEP   2021-02-11                   4.101550e+07
ALGM   2021-02-02                  -4.957500e+06
LESL   2021-02-08                  -7.231100e+07

                   quarter10_netinccmn_diff_median  \
ticker date
DQWS   2020-11-13                          10495.0
       2020-08-14                          16976.5
       2020-05-15                          23458.0
       2020-04-03                          11729.0
       2020-03-30                          23458.0
...                                            ...
LSPD   2021-02-04                      -23185000.0
FROG   2021-02-12                        1551000.0
STEP   2021-02-11                       41015500.0
ALGM   2021-02-02                       -4957500.0
LESL   2021-02-08                      -72311000.0

                   quarter10_netinccmn_diff_max  quarter10_netinccmn_diff_min  \
ticker date
DQWS   2020-11-13                       95618.0                      -56532.0
       2020-08-14                       95618.0                      -56532.0
       2020-05-15                       95618.0                      -56532.0
       2020-04-03                       95618.0                      -56532.0
       2020-03-30                       95618.0                      -56532.0
...                                         ...                           ...
LSPD   2021-02-04                   -23185000.0                   -23185000.0
FROG   2021-02-12                     1551000.0                     1551000.0
STEP   2021-02-11                    55663000.0                    26368000.0
ALGM   2021-02-02                     4764000.0                   -14679000.0
LESL   2021-02-08                   -72311000.0                   -72311000.0

                   quarter10_netinccmn_diff_std  sector  sicindustry  \
ticker date
DQWS   2020-11-13                  4.359313e+04       3          195
       2020-08-14                  4.548749e+04       3          195
       2020-05-15                  4.859416e+04       3          195
       2020-04-03                  4.937226e+04       3          195
       2020-03-30                  5.390834e+04       3          195
...                                         ...     ...          ...
LSPD   2021-02-04                  0.000000e+00      10          307
FROG   2021-02-12                  0.000000e+00      10          307
STEP   2021-02-11                  1.464750e+07       5          121
ALGM   2021-02-02                  9.721500e+06      10          263
LESL   2021-02-08                  0.000000e+00       2          250

                          y      pred     metric
ticker date
DQWS   2020-11-13  0.412941  1.188729   1.878689
       2020-08-14  3.250000  1.764145   0.457186
       2020-05-15  0.000000  1.227492        NaN
       2020-04-03 -0.476440  0.927045   2.945775
       2020-03-30  0.469231  1.287880   1.744661
...                     ...       ...        ...
LSPD   2021-02-04  0.841238  0.180177   0.785819
FROG   2021-02-12  0.023568  0.060123   1.551090
STEP   2021-02-11  0.322992  0.112765   0.650873
ALGM   2021-02-02  0.404578  0.067306   0.833638
LESL   2021-02-08 -0.013855  0.146037  11.540457

[19768 rows x 485 columns]

In [182]:
pd.merge(X, y, on='ticker', how='left')

,ticker,quarter2_revenue_mean,quarter2_revenue_median,quarter2_revenue_max,quarter2_revenue_min,quarter2_revenue_std,quarter2_revenue_diff_mean,quarter2_revenue_diff_median,quarter2_revenue_diff_max,quarter2_revenue_diff_min,...,quarter10_netinccmn_diff_median,quarter10_netinccmn_diff_max,quarter10_netinccmn_diff_min,quarter10_netinccmn_diff_std,sector,sicindustry,date,y,pred,metric
0,DQWS,235307.5,235307.5,249705.0,220910.0,14397.5,28795.0,28795.0,28795.0,28795.0,...,10495.0,95618.0,-56532.0,4.359313e+04,3,195,2020-11-13,0.412941,1.188729,1.878689
1,DQWS,235307.5,235307.5,249705.0,220910.0,14397.5,28795.0,28795.0,28795.0,28795.0,...,10495.0,95618.0,-56532.0,4.359313e+04,3,195,2020-08-14,3.250000,1.764145,0.457186
2,DQWS,235307.5,235307.5,249705.0,220910.0,14397.5,28795.0,28795.0,28795.0,28795.0,...,10495.0,95618.0,-56532.0,4.359313e+04,3,195,2020-05-15,0.000000,1.227492,NaN
3,DQWS,235307.5,235307.5,249705.0,220910.0,14397.5,28795.0,28795.0,28795.0,28795.0,...,10495.0,95618.0,-56532.0,4.359313e+04,3,195,2020-04-03,-0.476440,0.927045,2.945775
4,DQWS,235307.5,235307.5,249705.0,220910.0,14397.5,28795.0,28795.0,28795.0,28795.0,...,10495.0,95618.0,-56532.0,4.359313e+04,3,195,2020-03-30,0.469231,1.287880,1.744661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172697,LSPD,51552000.0,51552000.0,57611000.0,45493000.0,6059000.0,12118000.0,12118000.0,12118000.0,12118000.0,...,-23185000.0,-23185000.0,-23185000.0,0.000000e+00,10,307,2021-02-04,0.841238,0.180177,0.785819
172698,FROG,40787500.0,40787500.0,42689000.0,38886000.0,1901500.0,3803000.0,3803000.0,3803000.0,3803000.0,...,1551000.0,1551000.0,1551000.0,0.000000e+00,10,307,2021-02-12,0.023568,0.060123,1.551090
172699,STEP,245031500.0,245031500.0,247150000.0,242913000.0,2118500.0,4237000.0,4237000.0,4237000.0,4237000.0,...,41015500.0,55663000.0,26368000.0,1.464750e+07,5,121,2021-02-11,0.322992,0.112765,0.650873
172700,ALGM,150549000.0,150549000.0,164449000.0,136649000.0,13900000.0,27800000.0,27800000.0,27800000.0,27800000.0,...,-4957500.0,4764000.0,-14679000.0,9.721500e+06,10,263,2021-02-02,0.404578,0.067306,0.833638
172701,LESL,263159500.0,263159500.0,381313000.0,145006000.0,118153500.0,-236307000.0,-236307000.0,-236307000.0,-236307000.0,...,-72311000.0,-72311000.0,-72311000.0,0.000000e+00,2,250,2021-02-08,-0.013855,0.146037,11.540457

In [181]:
y

      ticker        date         y      pred     metric
0       DQWS  2020-11-13  0.412941  1.188729   1.878689
1       DQWS  2020-08-14  3.250000  1.764145   0.457186
2       DQWS  2020-05-15  0.000000  1.227492        NaN
3       DQWS  2020-04-03 -0.476440  0.927045   2.945775
4       DQWS  2020-03-30  0.469231  1.287880   1.744661
...      ...         ...       ...       ...        ...
19763   LSPD  2021-02-04  0.841238  0.180177   0.785819
19764   FROG  2021-02-12  0.023568  0.060123   1.551090
19765   STEP  2021-02-11  0.322992  0.112765   0.650873
19766   ALGM  2021-02-02  0.404578  0.067306   0.833638
19767   LESL  2021-02-08 -0.013855  0.146037  11.540457

[19768 rows x 5 columns]

In [18]:
y = y[leave_mask].reset_index(drop=True)
X = X[leave_mask].reset_index(drop=True)

mc_pipeline._eval(X=X.drop(['ticker', 'date'], axis=1),
           y=y['y'].values,
           groups=X['ticker'])

nan

In [ ]:
0.39497680805725816

In [17]:
mc_pipeline.export_core('models_data/diff')

In [6]:
imp_df = pd.DataFrame()
imp_df['column'] = mc_pipeline.model.columns
imp_df['importance'] = mc_pipeline.model.base_models[0].feature_importances_
imp_df = imp_df.sort_values('importance', ascending=False)[:]
imp_df[:10]

                               column  importance
135       quarter2_divyield_diff_mean          40
134             quarter2_divyield_std          38
481                       sicindustry          34
145   quarter2_currentratio_diff_mean          32
105            quarter2_rnd_diff_mean          32
256      quarter4_cashneq_diff_median          31
44                quarter2_ebitda_std          30
84        quarter2_workingcapital_std          27
404      quarter10_workingcapital_std          24
465  quarter10_currentratio_diff_mean          24

In [11]:
mc_pipeline = BasePipeline.load('models_data/ctb.pickle')
mc_df = mc_pipeline.execute(config, ticker_list)

In [8]:
mc_df

      ticker        date             y
0       DQWS  2020-11-13  4.195258e+09
1       DQWS  2020-08-14  4.008153e+09
2       DQWS  2020-05-15  4.053623e+09
3       DQWS  2020-04-03  4.149051e+09
4       DQWS  2020-03-30  4.065268e+09
...      ...         ...           ...
20071   AVIR  2020-12-10  7.639594e+09
20072   AVIR  2020-10-26  1.071128e+10
20073   LESL  2021-02-08  2.427790e+09
20074   LESL  2020-12-23  7.391225e+09
20075   LESL  2020-10-26  1.079197e+10

[20076 rows x 3 columns]